### ISSUE TITLE
Wildcard subdomains using the same session cookie

### ISSUE THREAD

**Issue by chadlieberman** [spro/simon#2]
local _, count = string.gsub(host, "%.", "")
if count > 1 then
    host = string.lower(string.gsub(host, "^%w*(.-)%.", ""))
end

**Comment by chadlieberman** [comment]
At least will work for alphanumeric subdomains...

**Comment by spro** [comment]
Closed with 10261f3c7a32c8b559d7554bde887d7853f90704
